package basico.task.management.enums;

public enum Status {

    DRAFT,
    ASSIGNED,
    ACCEPTED,
    BUDGET_SUBMITTED,
    IN_EXECUTION,
    REJECTED,
    REJECTED_BY_SUPPLIER,
    PENDING,
    APPROVED,
    REJECT_BUDGET,
    BUDGET_REVIEW,
    REVIEW_TASK,
    APPROVED_BUDGET,
    TASK_CMP_PENDING,
    TASK_CMP_APPROVED,
    TASK_CMP_REVIEW,
    PENDING_APPROVAL,
    TASK_COMPLETED,
    COMPLETED_BY_SUPPLIER,
    HOLD,
    INVOICE_PENDING,
    INVOICE_REJECTED_SUPPLIER,
    INVOICE_UPLOADED,
    INVOICE_ACCEPTED_TECH_USER,
    INVOICE_REJECT_TECH_USER,
    PROCESSED,
    NEW;

}
